In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv("trades_round_3_day_0.csv", sep=";")

In [13]:
df

,timestamp,buyer,seller,symbol,currency,price,quantity
0,0,NaN,NaN,CROISSANTS,SEASHELLS,4322.0,8
1,0,NaN,NaN,DJEMBES,SEASHELLS,13494.0,3
2,0,NaN,NaN,RAINFOREST_RESIN,SEASHELLS,9992.0,8
3,200,NaN,NaN,RAINFOREST_RESIN,SEASHELLS,10008.0,2
4,300,NaN,NaN,KELP,SEASHELLS,2029.0,6
...,...,...,...,...,...,...,...
18118,999800,NaN,NaN,DJEMBES,SEASHELLS,13410.0,3
18119,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,515.0,11
18120,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,277.0,11
18121,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,94.0,11
18122,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,764.0,11

In [15]:
df.fillna(0)

,timestamp,buyer,seller,symbol,currency,price,quantity
0,0,0.0,0.0,CROISSANTS,SEASHELLS,4322.0,8
1,0,0.0,0.0,DJEMBES,SEASHELLS,13494.0,3
2,0,0.0,0.0,RAINFOREST_RESIN,SEASHELLS,9992.0,8
3,200,0.0,0.0,RAINFOREST_RESIN,SEASHELLS,10008.0,2
4,300,0.0,0.0,KELP,SEASHELLS,2029.0,6
...,...,...,...,...,...,...,...
18118,999800,0.0,0.0,DJEMBES,SEASHELLS,13410.0,3
18119,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,515.0,11
18120,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,277.0,11
18121,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,94.0,11
18122,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,764.0,11

In [22]:
#Enlever tout ce qui n'est pas lié au volcanic rock en filtrant par r

df_vr= df[df['symbol'].str.contains('VOLCANIC_ROCK')]

In [24]:
df_vr

,timestamp,buyer,seller,symbol,currency,price,quantity
12,1200,NaN,NaN,VOLCANIC_ROCK,SEASHELLS,10505.0,10
24,2000,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,13
25,2000,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,1
26,2000,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,1
27,2000,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,264.0,13
...,...,...,...,...,...,...,...
18108,999000,NaN,NaN,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,769.0,11
18119,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,515.0,11
18120,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,277.0,11
18121,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,94.0,11
18122,999900,NaN,NaN,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,764.0,11

In [26]:
df_vr.fillna(0)

,timestamp,buyer,seller,symbol,currency,price,quantity
12,1200,0.0,0.0,VOLCANIC_ROCK,SEASHELLS,10505.0,10
24,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,13
25,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,1
26,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,1
27,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,264.0,13
...,...,...,...,...,...,...,...
18108,999000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,769.0,11
18119,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,515.0,11
18120,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,277.0,11
18121,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,94.0,11
18122,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,764.0,11

In [30]:
#obligé de faire des dataframe pour chaque type pour arriver à une bonne représentation

vr= df_vr[df_vr['symbol'] == 'VOLCANIC_ROCK']

In [32]:
vr = vr.fillna(0)

In [34]:
vr

       timestamp  buyer  seller         symbol   currency    price  quantity
12          1200    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10505.0        10
50          2800    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10472.0         8
112         4900    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10464.0        10
113         5000    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10462.0         6
136         6800    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10432.0        10
...          ...    ...     ...            ...        ...      ...       ...
17966     993400    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10543.0         9
18006     995000    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10536.0         5
18053     996700    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10521.0         8
18058     996800    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10522.0         9
18087     998400    0.0     0.0  VOLCANIC_ROCK  SEASHELLS  10518.0         9

[637 rows x 7 columns]

## VOUCHER 9500

In [36]:
vr_9500 = df_vr[df_vr['symbol'] == 'VOLCANIC_ROCK_VOUCHER_9500']

In [38]:
vr_9500 = vr_9500.fillna(0)

In [40]:
vr_9500

,timestamp,buyer,seller,symbol,currency,price,quantity
33,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,993.0,13
34,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,993.0,1
35,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,993.0,1
45,2600,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,975.0,10
63,3100,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,973.0,10
...,...,...,...,...,...,...,...
18034,995700,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,1030.0,14
18043,996400,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,1023.0,10
18064,996900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,1021.0,14
18082,998000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,1017.0,10
18107,999000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9500,SEASHELLS,1019.0,11

## VOUCHER 9750

In [42]:
vr_9750 = df_vr[df_vr['symbol'] == 'VOLCANIC_ROCK_VOUCHER_9750']

In [44]:
vr_9750 = vr_9750.fillna(0)

In [46]:
vr_9750

,timestamp,buyer,seller,symbol,currency,price,quantity
36,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,743.0,13
37,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,743.0,1
38,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,743.0,1
46,2600,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,725.0,10
67,3100,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,724.0,10
...,...,...,...,...,...,...,...
18044,996400,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,773.0,10
18065,996900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,772.0,14
18083,998000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,767.0,10
18108,999000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,769.0,11
18122,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_9750,SEASHELLS,764.0,11

## VOUCHER 10000

In [48]:
vr_10000 = df_vr[df_vr['symbol'] == 'VOLCANIC_ROCK_VOUCHER_10000']

In [50]:
vr_10000 = vr_10000.fillna(0)

In [52]:
vr_10000

,timestamp,buyer,seller,symbol,currency,price,quantity
24,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,13
25,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,1
26,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,496.0,1
42,2600,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,479.0,10
54,3100,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,478.0,10
...,...,...,...,...,...,...,...
18040,996400,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,525.0,10
18061,996900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,523.0,14
18079,998000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,520.0,10
18104,999000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,520.0,11
18119,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10000,SEASHELLS,515.0,11

## VOUCHER 10250

In [54]:
vr_10250 = df_vr[df_vr['symbol'] == 'VOLCANIC_ROCK_VOUCHER_10250']

In [56]:
vr_10250 = vr_10250.fillna(0)

In [58]:
vr_10250

,timestamp,buyer,seller,symbol,currency,price,quantity
27,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,264.0,13
28,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,264.0,1
29,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,264.0,1
43,2600,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,249.0,10
57,3100,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,248.0,10
...,...,...,...,...,...,...,...
18041,996400,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,285.0,10
18062,996900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,284.0,14
18080,998000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,280.0,10
18105,999000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,281.0,11
18120,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10250,SEASHELLS,277.0,11

## VOUCHER 10500

In [60]:
vr_10500 = df_vr[df_vr['symbol'] == 'VOLCANIC_ROCK_VOUCHER_10500']

In [62]:
vr_10500 = vr_10500.fillna(0)

In [64]:
vr_10500

,timestamp,buyer,seller,symbol,currency,price,quantity
30,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,93.0,13
31,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,93.0,1
32,2000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,93.0,1
44,2600,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,85.0,10
60,3100,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,85.0,10
...,...,...,...,...,...,...,...
18042,996400,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,99.0,10
18063,996900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,98.0,14
18081,998000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,96.0,10
18106,999000,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,96.0,11
18121,999900,0.0,0.0,VOLCANIC_ROCK_VOUCHER_10500,SEASHELLS,94.0,11

## VISUALISATION PRIX SPOT + PRIX OPTIONS (VOUCHERS)

In [70]:
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.palettes import Category10
from bokeh.layouts import layout 


#Application de la transformée de fourier pour enlever fréquences parasites et lisser les courbes 

def filtre_fourier(signal, seuil= 0.01):
    fft_vals = np.fft.fft(signal)
    fft_freqs = np.fft.fftfreq(len(signal))
    fft_vals[np.abs(fft_freqs) > seuil] = 0
    signal_filtré = np.fft.ifft(fft_vals)
    return np.real(signal_filtré)

#Liste des produits

produits = ['VOLCANIC_ROCK' , 'VOLCANIC_ROCK_VOUCHER_9500', 'VOLCANIC_ROCK_VOUCHER_10000', 'VOLCANIC_ROCK_VOUCHER_10250','VOLCANIC_ROCK_VOUCHER_10500']


if 'symbol' not in df_vr.columns:
    raise KeyError("La colonne 'symbole' est absente du DataFrame")
#Initialisation Figure
p = figure(title = "Représentation Prix Spot et Prix Strike + Premium avec Lissage FFT et rapprochement spot des options pour observation", x_axis_label= "Timestamp", y_axis_label= "Mid Price",
           width = 1000, height = 500)

#Couleurs des courbes
colors = ['green', 'blue', 'orange', 'purple', 'red', 'black']

#Traçage de chaque produit , prod étant un produit dans la liste "produits"
prod = None
for i, prod in enumerate(produits):
   
    df_filtered = df_vr[df_vr['symbol'] == prod].copy()
    df_filtered['price']= filtre_fourier (df_filtered['price'])
    
    if prod == 'VOLCANIC_ROCK':
        df_filtered['price'] = df_filtered['price']
    elif prod == 'VOLCANIC_ROCK_VOUCHER_9500':
        df_filtered['price'] = df_filtered['price'] + 9500
    elif prod == 'VOLCANIC_ROCK_VOUCHER_9750':
        df_filtered['price'] = df_filtered['price'] + 9750
    elif prod == 'VOLCANIC_ROCK_VOUCHER_10000':
        df_filtered['price'] = df_filtered['price'] + 10000

    
    

    #Comme sur excel quand tu mets les données avec lesquelles tu vas faire ta figure 
    source = ColumnDataSource(df_filtered)

    line = p.line('timestamp' , 'price', source=source, line_width = 2, legend_label=prod, color = colors[i])

    hover  = HoverTool(tooltips = [ ("Produit" , prod) , ("Time", "@timestamp") , ("Mid Price", "@price{0.00}") ],
    renderers = [line])
    p.add_tools(hover)
p.legend.location = "top_left"
p.legend.click_policy = "hide" #Pour cacher/afficher les courbes
p.toolbar.autohide= True

show(p)